### PR TITLE
Small typings fixes

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by rom1504** [comment]
Are you sure it's not a bug if it's undefined ?

**Comment by u9g** [comment]
> Are you sure it's not a bug if it's undefined ?

No. If the player doesn't exist, the player is undefined, ie:
```js
const a = {}
console.log(a.b) // => undefined
```
And when the entity gets destroyed, we just set the entity to null: https://github.com/PrismarineJS/mineflayer/blob/u9g-patch-4/lib/plugins/entities.js#L270

**Comment by rom1504** [comment]
> No. If the player doesn't exist, the player is undefined, ie:

how can the player not exist?

**Comment by u9g** [comment]
> > No. If the player doesn't exist, the player is undefined, ie:
> 
> how can the player not exist?

if the player isn't on the server, they don't exist... What If Notch never logged onto your server, he doesn't exist as far as we know.

**Comment by rom1504** [comment]
@u9g then why would it be in this.players ?

**Pull request closed without merging**
