### PR TITLE
remake crafting plugin

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Review by nickelpro — APPROVED** [review]
LGTM with one reservation: I can't come up with a complete explanation for what connection these changes have on the `useChests` test. I think this code should get merged regardless, but I think don't think the `useChests` test is fixed by them. You can see similar random flailing with regards to useChest in the 1.17 PR.

**Review by u9g — COMMENTED** [review]
stop using openContainer to open the crafting table

**Comment by rom1504** [comment]
this is almost done, why not finish it ?

**Comment by rom1504** [comment]
ci failing

**Comment by rom1504** [comment]
Old

**Pull request closed without merging**
