### PR TITLE
Add nether test

### LINKED ISSUE #2614: 1.8.9 chunk errors
Hey, I was testing some things on the bot when I realised that whenever I put a wooden sign (on a wall or on the ground) it crashes.

This is the error it gives me:

```
node:internal/buffer:86
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 10239. Received 10583
    at new NodeError (node:internal/errors:371:5)
    at boundsError (node:internal/buffer:86:9)
    at Buffer.readUInt8 (node:internal/buffer:252:5)
    at readUInt4LE (C:\Users\deivi\WebstormProjects\sigmaBot\node_modules\uint4\index.js:23:23)
    at writeUInt4LE (C:\Users\deivi\WebstormProjects\sigmaBot\node_modules\uint4\index.js:34:28)
    at Section.setSkyLight (C:\Users\deivi\WebstormProjects\sigmaBot\node_modules\prismarine-chunk\src\pc\1.8\section.js:123:5)
    at Chunk.setSkyLight (C:\Users\deivi\WebstormProjects\sigmaBot\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:145:33)
    at Chunk.setBlock (C:\Users\deivi\WebstormProjects\sigmaBot\node_modules\prismarine-chunk\src\pc\1.8\chunk.js:79:42)
    at Client.<anonymous> (C:\Users\deivi\WebstormProjects\sigmaBot\node_modules\mineflayer\lib\plugins\blocks.js:406:12)
    at Client.emit (node:events:394:28) {
  code: 'ERR_OUT_OF_RANGE'
}
```

The bot.version is 1.8.9, I have tried doing this with a bot without any listener or functions and it happens again.

It just crashes when there is a sign close or when you place a sign. Same error every time. Removing the sign makes the bot not crash when loading the chunk.

### PR DESCRIPTION
**Pull request by frej4189**
Clone of sign test, but it teleports the bot to nether before starting the test, and teleports it back to overworld before finishing.

Primarily intended to verify that https://github.com/PrismarineJS/prismarine-chunk/pull/209 also closes #2614

### CODE REVIEW

**Comment by extremeheat** [comment]
CI is failing, you can update the dependency in package.json to point to your GitHub branch to test if it would be passing with your PR

**Comment by frej4189** [comment]
W.I.P

**Comment by frej4189** [comment]
> CI is failing, you can update the dependency in package.json to point to your GitHub branch to test if it would be passing with your PR

CI appears to fail to install dependencies with this configuration for some reason

**Comment by rom1504** [comment]
old and fails

please re-open if you want to finish it

**Comment by frej4189** [comment]
CI failing due to running prior to #2937 

Re-running CI should pass

**Comment by rom1504** [comment]
rerunning, but I'm afraid blocked by #2047

**Comment by frej4189** [comment]
> rerunning, but I'm afraid blocked by #2047 

That issue is closed?

**Comment by frej4189** [comment]
CI failing for different reasons now. Seems there have been breaking changes to signs since this PR was created

**Comment by rom1504** [comment]
I meant #3129

**Pull request merged**
