### PR TITLE
Added containerItems() in class Chest

### PR DESCRIPTION
**Pull request by olzx**
Hi, in Chest's examples this containerItems () method was used, but ts file (in the tooltips) it is not there, so I decided to add

### CODE REVIEW

**Comment by u9g** [comment]
this isnt the right fix, the window object should extend prismarine-window

**Comment by olzx** [comment]
> this isnt the right fix, the window object should extend prismarine-window

But how does this relate to my fix?

**Comment by u9g** [comment]
the prismarine-window class already has the .containerItems funxtion, so this change would be unnecessary

**Comment by olzx** [comment]
> the prismarine-window class already has the .containerItems function, so this change would be unnecessary

Definitely! 
I didn’t see this hint because I am writing a plugin (in another file, but they are not presented there) I did not notice, but I saw. Thanks

**Pull request closed without merging**
