### PR TITLE
*: update dep and make tweaks

### PR DESCRIPTION
**Pull request by VoltrexKeyva**
- Update the `typed-emitter` dependency to it's latest version.
- The `BotEvents` interface is supposed to be a type instead of an interface, required by the latest versions of the `typed-emitter` dependency.
- Set the `esModuleInterop` compiler option to `true` required to import type definitions of some of the updated dependencies.

### CODE REVIEW

**Comment by extremeheat** [comment]
Bumping the versions here will have no effect on installs as npm uses semantic versioning and we use the `^` designator.  Read https://docs.npmjs.com/about-semantic-versioning

The event emitter change is inappropriate as you lose validity checking, such as typos in the event name.

As for the type config changes, the `tsconfig.json` is used for the linter (ts-standard), lint CI seems passing so can you explain the need for the change?

**Comment by VoltrexKeyva** [comment]
> Bumping the versions here will have no effect on installs as npm uses semantic versioning and we use the `^` designator.  Read https://docs.npmjs.com/about-semantic-versioning

I'm well aware, I only updated them along with the other ones that do have an effect just for convenience.

> The event emitter change is inappropriate as you lose validity checking, such as typos in the event name.

Thank you for pointing that out, I misunderstood the change the new versions of `typed-emitter` requires, pushing a fix for that.

> As for the type config changes, the `tsconfig.json` is used for the linter (ts-standard), lint CI seems passing so can you explain the need for the change?

The TypeScript compiler chokes when trying to import the type definitions of some of the other modules because they're exported with `export =`, the lint CI passes because I made that change.

**Review by extremeheat — APPROVED** [review]

**Comment by rom1504** [comment]
> I'm well aware, I only updated them along with the other ones that do have an effect just for convenience.

So we don't know what change is useful since you changed too many

**Comment by VoltrexKeyva** [comment]
> > I'm well aware, I only updated them along with the other ones that do have an effect just for convenience.
> 
> So we don't know what change is useful since you changed too many

I can update the commit message to clarify what dependency updates are actually useful/does have an effect if that's better.

**Comment by rom1504** [comment]
Simply undo the unneeded updates

**Comment by VoltrexKeyva** [comment]
> Simply undo the unneeded updates

Done.

**Comment by rom1504** [comment]
there are conflicts

**Pull request closed without merging**
