### PR TITLE
fix titles and actionbar for new versions

### PR DESCRIPTION
**Pull request by KalmeMarq**

### CODE REVIEW

**Comment by KalmeMarq** [comment]
but what if a subtitle isn't emitted? And they are different packets now so how do I put them together anyway?

**Comment by KalmeMarq** [comment]
but how does the person know which is which?

**Comment by KalmeMarq** [comment]
> Do they care that there is a difference? But you do have a point. Correct me if I am wrong, but in vanilla, there isn't a difference when the server sends you a title and a subtitle, so that is probably why it was included together
> 
> You are welcome to add support for the other packet actions for titles.

but if it didn't have a difference how would the server know what to send to the other players? it must have a difference somewhere cuz it even has diff packets.

**Comment by extremeheat** [comment]
The minecraft protocols they use are not efficient (or stable), so making abstractions that maximize future compatibility is important. See how boss bars are currently handled for an example

**Comment by rom1504** [comment]
@KalmeMarq want to finish this?

**Comment by rom1504** [comment]
too old, please reopen if you want to finish

**Pull request closed without merging**
