### PR TITLE
add example for using the node:readline module

### PR DESCRIPTION
**Pull request by Jovan-04**

### CODE REVIEW

**Comment by Jovan-04** [comment]
double checked the bot on vanilla servers for both 1.19 & 1.19.2. works as intended with no issues.

**Comment by rom1504** [comment]
we have too many examples ,let's start doing things right

can you create a subfolder like examples/cli and put your example there ?

**Comment by Jovan-04** [comment]
can do. I think there's a repl example that can go in there too. 

also, i bet there's a better way to organize the examples we have now, along with making sure they're all up-to-date. i'll think on that. 

i'd like to contribute, but i don't think i'm experienced with mineflayer or js to do any serious work on the source code.

**Comment by rom1504** [comment]
Moving the examples would definitely be appreciated

Someone tried once but didn't finish

Also having a doc page pointing to relevant example for relevant features would help

But first let's finish this PR

**Comment by Jovan-04** [comment]
i think that should do it

**Comment by rom1504** [comment]
Yes feel free to do in another PR

**Pull request merged**
