### PR TITLE
Fix furnace and add tests

### LINKED ISSUE #1350: Furnaces are "full" when they're empty
The [FAQ](https://github.com/PrismarineJS/mineflayer/blob/master/docs/FAQ.md) doesn't contain a resolution to my issue 

## Versions
 - mineflayer: 2.29.1
 - server: vanilla 1.12.2
 - node: (not specified in package.json, likely latest)

## Detailed description of the problem
When a bot tries to put an item into a furnace, it errors with "Destination full"

## What did you try yet?

I tried asking the Discord for help, removing async things from the code.

## Your current code
Example chest.js is subject to this problem as well.
```javascript
               cmds.gotoblock("furnace", () => {
                    let furnace = bot.openFurnace(craftingTable)
                    furnace.on('open', () => {
                        console.log("Opened the furnace.")
                        console.log(furnace.window)
                        let hasFuel = furnace.fuelItem()
                        function cont(err) {
                            if (err) {
                                console.log(err)
                                return
                            }
                            console.log("Putting in the item.")
                            furnace.putInput(tosmelt.type, tosmelt.metadata, tosmelt.count, async (err) => {
                                if (err) {
                                    console.log(err)
                                    return
                                }
                                if (quantity != 0) {
                                    setTimeout(() => {
                                        console.log("Taking the output.")
                                        furnace.takeOutput(callback)
                                    }, 10000 * quantity)
                                } else {
                                    callback()
                                }
                            })
                        }
                        if (!hasFuel) {
                            if (fuel) {
                                console.log("Placing fuel.")
                                furnace.putFuel(fuel.type, fuel.metadata, fuel.count, cont)
                            } else {
                                console.log("I have no fuel.")
                                return
                            }
                        } else {
                            console.log("Has fuel, continuing.")
                            cont()
                        }
                    })})
```

## Expected behavior
I expected the bot to place items inside the furnace.

## Additional context
When the bot disconnects, the item is dropped.

### PR DESCRIPTION
**Pull request by imharvol**
Closes #1350

### CODE REVIEW

**Comment by ImHarvol** [comment]
Tested it and it seems to work correctly. I'll also work on tests for the furnace's functions.

**Comment by Bottinator22** [comment]
Works! It's no longer blind on whether or not the furnace is full.

**Review by wvffle — COMMENTED** [review]
Only missing tests ;)

**Comment by ImHarvol** [comment]
I think I'm going to add a property like fuelSeconds and progressSeconds that returns how much time is left.

**Comment by ImHarvol** [comment]
I've checked and the porkchop indeed is cooked, but mineflayer doesn't update the window.

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
