### PR TITLE
Try to fix confirmTransaction for broken servers

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by u9g** [comment]
Not sure this works, hoping for confirmation from someone who was dealing with this.

**Review by Hazuki-san — APPROVED** [review]
Issue is fixed on my test server!

**Comment by Hazuki-san** [comment]
sometimes i get this
```
C:\Users\Aoba\Desktop\Developer_Tools\a\node_modules\minecraft-protocol\src\transforms\framing.js:67
          } else { throw e }
                   ^

AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(click.id <= actionId)

    at confirmTransaction (C:\Users\Aoba\Desktop\Developer_Tools\a\node_modules\mineflayer\lib\plugins\inventory.js:342:12)
    at Client.<anonymous> (C:\Users\Aoba\Desktop\Developer_Tools\a\node_modules\mineflayer\lib\plugins\inventory.js:451:5)
    at Client.emit (node:events:329:20)
    at FullPacketParser.<anonymous> (C:\Users\Aoba\Desktop\Developer_Tools\a\node_modules\minecraft-protocol\src\client.js:91:12)
    at FullPacketParser.emit (node:events:329:20)
    at addChunk (C:\Users\Aoba\Desktop\Developer_Tools\a\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\Aoba\Desktop\Developer_Tools\a\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at FullPacketParser.Readable.push (C:\Users\Aoba\Desktop\Developer_Tools\a\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at FullPacketParser.Transform.push (C:\Users\Aoba\Desktop\Developer_Tools\a\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at FullPacketParser._transform (C:\Users\Aoba\Desktop\Developer_Tools\a\node_modules\protodef\src\serializer.js:89:10) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

**Comment by rom1504** [comment]
looks broken

**Pull request closed without merging**
