### PR TITLE
Add bot.entityInSight() (recreation of #1371)

### PR DESCRIPTION
**Pull request by au5ton**
This is a re-opening of https://github.com/PrismarineJS/mineflayer/pull/1371 after making the changes requested in: https://github.com/PrismarineJS/mineflayer/pull/1371#issuecomment-712040319

I would've used the original pull request, but the author's GitHub account was deleted, so I wasn't sure how to go about doing that.

This worked well for me in my limited testing.

### CODE REVIEW

**Comment by extremeheat** [comment]
Dupe of https://github.com/PrismarineJS/mineflayer/pull/2077 ?

**Comment by extremeheat** [comment]
This implementation seems cleaner with a width feature though. Making the name match the current block methods sounds like a good idea, like `entityAtCursor()` in the other PR

**Comment by au5ton** [comment]
> This implementation seems cleaner with a width feature though. Making the name match the current block methods sounds like a good idea, like `entityAtCursor()` in the other PR

Are there any changes you'd like me to make, maybe specifically with the naming? It tried to follow the convention I saw in the other methods.

After looking at the other PR (#2077 ) it looks like I forgot to update the API docs, too.

**Comment by u9g** [comment]
If you can make a test that would be great!

**Comment by extremeheat** [comment]
This does not seem to test for obstructions. entityInSight() may return something even if a wall is in front of the bot.

**Comment by rom1504** [comment]
add test or example

**Comment by rom1504** [comment]
please re-open if you want to finish it

**Pull request closed without merging**
