### PR TITLE
Multiple.js example improved

### PR DESCRIPTION
**Pull request by Vistril**
The provided multiple.js hardly works and no parent object for the bots, meaning they can't do anything.
My code allows for modular usernames, quantity and password field if needed.
Uses a loop instead of an interval so crashing probability is lower.

### CODE REVIEW

**Comment by rom1504** [comment]
Why do you think a loop is better than an interval ?
The interval prevent bots to all start exactly at the same time, overloading the CPU and preventing the bots to start.

Didn't you notice that when starting many bots ?

**Comment by Vistril** [comment]
Personally, I had no CPU load issues. However, if this is what should be done, then I can change it to use a timeout and interval. I just don't like how the current example doesn't allow for a usable multi-client object.

**Comment by rom1504** [comment]
Try to connect 50 bots, you'll see it.

**Comment by Vistril** [comment]
I've connected more than 50

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/issues/710 shows the interval is required

**Pull request closed without merging**
