### PR TITLE
Add TR translation.

### PR DESCRIPTION
**Pull request by KaffinPX**

### CODE REVIEW

**Comment by KaffinPX** [comment]
Ill update it for better turkish later, its only first time :)

**Review by rom1504 — CHANGES_REQUESTED** [review]
lot of non translated content

**Comment by KaffinPX** [comment]
Ill work on later, can u pull these?

**Comment by KaffinPX** [comment]
I can make draft here if u want?

**Comment by rom1504** [comment]
I think it's better to merge this when it's reasonably complete (at least the readme)
feel free to continue working on this in this PR

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
