### PR TITLE
French translations

### PR DESCRIPTION
**Pull request by Creeper09**
I started to translate the readme file in french, there is still more work to be done

### CODE REVIEW

**Comment by Creeper09** [comment]
Hello, I am genuinely sorry for taking that much time on a single pull request, I'm lazying around way too much and I'll get it finished by the end of the week

**Comment by KaffinPX** [comment]
Bruh you removed turkish from langList
image

**Comment by Creeper09** [comment]
> Bruh you removed Turkish from langList
> image

No worry, I did not, since this branch is old, the newer translation haven't been added in this version, but I'll make sure to fix that

**Review by rom1504 — APPROVED** [review]

**Comment by rom1504** [comment]
can you please resolve conflicts ? it's ok if it's not finished, let's still merge

**Comment by Creeper09** [comment]
> can you please resolve conflicts ? it's ok if it's not finished, let's still merge

Oh- Right totally forgot it again

**Comment by Creeper09** [comment]
The only conflict left is because I added the french link to the README.md, should I undo that aswell?

**Comment by Creeper09** [comment]
It is all done, and ready to be merged

**Review by rom1504 — CHANGES_REQUESTED** [review]
Can you please undo most of these changes you did to readme.md ?

**Comment by Creeper09** [comment]
Done

**Comment by KaffinPX** [comment]
Are u Reverso from idleyHost?

**Comment by Creeper09** [comment]
> Are u Reverso from idleyHost?

No not at all sorry

**Comment by rom1504** [comment]
still some changes to undo in readme.md

**Comment by Creeper09** [comment]
> still some changes to undo in readme.md

What is next?

**Comment by rom1504** [comment]
look at https://github.com/PrismarineJS/mineflayer/pull/1643/files : why are there changes to readme.md ?

**Comment by rom1504** [comment]
I think restarting this from master is the best way to go here.
Just make a new branch from master, copy your readme_fr file and adapt the rest

**Comment by Creeper09** [comment]
> I think restarting this from master is the best way to go here.
> Just make a new branch from master, copy your readme_fr file and adapt the rest

I'll do that right away, sorry for being so absent the last weeks

**Pull request closed without merging**
