### PR TITLE
Task Queue Utility

### PR DESCRIPTION
**Pull request by TheDudeFromCI**
This is a helpful utility object that allows players to define a list of async tasks to perform without needing to working about making a nested pyramid of callbacks. This adds a procedural style, much closer to what new programmers are used to coding with, so it'll help make the transition to callbacks a bit easier. Plus, it looks much nicer.

### CODE REVIEW

**Comment by Karang** [comment]
I think this pr is a good idea. But I don't see what you mean about pworld : it has both a sync and async api. The sync pworld was added especially for mineflayer

**Comment by rom1504** [comment]
Hi,
I think adding such an example is useful to help people with async.
However I don't think it makes sense to add this utility.
I think it would be better in the example to use some existing lib such as https://caolan.github.io/async/v3/ or to use promises. A third way can be to put this queue inside the example.

It does not make a lot of sense to maintain this kind of task queue inside mineflayer as it doesn't contain a good subset of what people may want to do with async and I bet we would have to add many things to it, eventually leading to having some kind of clone of async.js

**Comment by rom1504** [comment]
Putting the queue in the example might be a reasonable choice, to show that implementing such a queue is one way to handle async but not the only way (and it could be good to talk about the other ways in comments in the example)

**Comment by rom1504** [comment]
Why close it ? I do mean adding the example is useful

**Comment by wvffle** [comment]
Indeed, there are libraries that do even more than this util, I opt for adding an example both in examples/ and tutorial

**Pull request closed without merging**
