### PR TITLE
1.17

### PR DESCRIPTION
**Pull request by rom1504**
@u9g

### CODE REVIEW

**Comment by rom1504** [comment]
needs to fix conflicts and lint at least

**Comment by rom1504** [comment]
follow up of https://github.com/PrismarineJS/mineflayer/pull/1993

**Comment by rom1504** [comment]
please PR to that @nickelpro if needed

**Comment by rom1504** [comment]
current state of CI:
* non 1.17.1 versions: failing with OOM on enchant
* 1.17.1 :  
  *  fishing timing out
  * trade 0 != 40
  * use chest failing with "chestLidMove emitted twice"

cc @u9g @nickelpro

**Comment by nickelpro** [comment]
This is very much rough code WIP, not intended to be mergable at all. That's why I haven't even opened a PR for it. When all tests pass and the codebase is approaching a finished state I'll open a PR from my branch

**Comment by rom1504** [comment]
> This is very much rough code WIP, not intended to be mergable at all. That's why I haven't even opened a PR for it. When all tests pass and the codebase is approaching a finished state I'll open a PR from my branch

could you please open a PR from your branch to 1.17 branch of mineflayer ?
it's ok if it's not ready, at least you see the CI running

and please take this 1.17 branch as a starting point, not the previous branch, to help with the git situation

**Comment by rom1504** [comment]
moving to https://github.com/PrismarineJS/mineflayer/pull/2110

**Review by idk787 — COMMENTED** [review]
Hi i wass wondering how do iset it up?

**Pull request closed without merging**
