### PR TITLE
Import changedSlots computation from prismarine-windows

### PR DESCRIPTION
**Pull request by kaduvert**
moves the slot-comparing calculation of changedSlots here because it's of no use in prismarine-windows
the clicks can still return changedSlots directly to save computation. some of them do

depends on https://github.com/PrismarineJS/prismarine-windows/pull/102 for ci

### CODE REVIEW

**Comment by rom1504** [comment]
CI fails

**Comment by kaduvert** [comment]
> CI fails

yes, because
> depends on https://github.com/PrismarineJS/prismarine-windows/pull/102 for ci

**Comment by kaduvert** [comment]
added the primsarine-windows pr as dependency and fixed some minor bugs.
ci passes @rom1504

**Comment by rom1504** [comment]
ok thanks

**Pull request merged**
