### PR TITLE
Add getExplosionDamages() function

### PR DESCRIPTION
**Pull request by Karang**
Sources:
https://minecraft.fandom.com/wiki/Explosion
https://minecraft.fandom.com/wiki/Armor#Damage_protection
https://minecraft.fandom.com/wiki/Attribute
https://github.com/extremeheat/extracted_minecraft_data/blob/client1.16.4/client/net/minecraft/world/level/Explosion.java#L198
https://github.com/extremeheat/extracted_minecraft_data/blob/client1.16.4/client/net/minecraft/world/damagesource/CombatRules.java
https://github.com/kami-blue/client/blob/master/src/main/kotlin/org/kamiblue/client/util/combat/CrystalUtils.kt#L87
https://github.com/kami-blue/client/blob/master/src/main/kotlin/org/kamiblue/client/util/combat/CombatUtils.kt#L47

### CODE REVIEW

**Comment by rom1504** [comment]
that looks good but:
* is there any sub package where this could fit ?
* could we add some test?

**Comment by LINKdiscordd** [comment]
Yes it would fit into mineflayer-autocrystal

**Comment by u9g** [comment]
or prismarine-physics

**Comment by LINKdiscordd** [comment]
or flying-squid

**Comment by u9g** [comment]
no, this wouldnt fit in flying squid since we need it to be used by both mineflayer and flying squid

**Comment by LINKdiscordd** [comment]
oh sorry my bad lol

**Comment by LINKdiscordd** [comment]
also for the test karang can add one where the bot always will recieve a set amount of damage and if the calculation of the function doesn't match up with the damage that is expected it fails essentially

at least thats how I would do it

**Comment by Karang** [comment]
prismarine-physics would make sense yes, but i think its better to move it once its feature complete. At least in mineflayer we have access to everything we need to develop it. To finish it properly we need to implement the whole attribute system and that's a big chunk (outside of the scope of this PR). I'll add the supportFeatures() and a small test then it'll be ready to be merged.

**Comment by rom1504** [comment]
this at least needs doc before merging

**Review by KaffinPX — CHANGES_REQUESTED** [review]
Adding events and functions to doc will useful

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
