### PR TITLE
Update README_TR.md

### PR DESCRIPTION
**Pull request by AhmetEsad**
whoever translated this file in the first place most likely used some kinda translator because the translations were weird (+ had many grammatical errors)
also I know it doesn't mean the same thing but I don't think there's a more accurate translation of "bounding box" than "hayali kutucuk" (that would be an "imaginary box" in English)

### CODE REVIEW

**Comment by KaffinPX** [comment]
Hayır kullanmadım :)

**Comment by KaffinPX** [comment]
LGTM @rom1504

**Comment by AhmetEsad** [comment]
> Hayır kullanmadım :)

sorry, didn't mean to be offensive

**Comment by KaffinPX** [comment]
Ya my translate was weird bcs i made it in 30 minutes XD No problem

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
