### PR TITLE
Auto Version

### PR DESCRIPTION
**Pull request by plexigras**

### CODE REVIEW

**Comment by rom1504** [comment]
Does that work ?
(https://github.com/PrismarineJS/mineflayer/issues/468 is the issue tracking this)
in particular : does options.version get updated to the correct version ? it's needed by plugins https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/entities.js#L27

**Comment by plexigras** [comment]
> Does that work ?

i tried it on 1.9.4, 1.10.2, 1.11.2 and 1.12

it only didn't work on 1.10.2 but it didn't work on master either

**Comment by rom1504** [comment]
what's the error on 1.10.2 ?

**Comment by rom1504** [comment]
Ah I know, it doesn't exist.
1.11.2 exists.

**Comment by rom1504** [comment]
Thanks !

**Pull request merged**
