### PR TITLE
Update Debug Info

### PR DESCRIPTION
**Pull request by u9g**
The old method doesn't work + this shows how to make debug work w/ cmd & powershell

### CODE REVIEW

**Comment by extremeheat** [comment]
A cross platform solution is to define it in node. At the top of your main node.js file, add `process.env.DEBUG = 'minecraft-protocol'`.

Also, I just tried it and the current code on the README works fine for me. Can you run `console.log(JSON.stringify(process.env.DEBUG))` to check the output?

**Comment by u9g** [comment]
> A cross platform solution is to define it in node. At the top of your main node.js file, add `process.env.DEBUG = 'minecraft-protocol'`.
> 
> Also, I just tried it and the current code on the README works fine for me. Can you run `console.log(JSON.stringify(process.env.DEBUG))` to check the output?

Sure. Unrelated, but how are tests failing? 😕

**Comment by extremeheat** [comment]
Not sure, you can try to run them again

**Comment by rom1504** [comment]
can you rebase to see if it fixes tests ?

**Comment by u9g** [comment]
lol how does this still fail tests

**Pull request closed without merging**
