### PR TITLE
Support node < 10.0.0

### PR DESCRIPTION
**Pull request by FroggyYT**
Fix error on line 17
Unexpected Token {

### CODE REVIEW

**Comment by wvffle** [comment]
This is not an error, this is a syntax that is available from node v10.0.0

**Comment by rom1504** [comment]
Lts is node 12.
Is there something inside npm or some module to check the user node and
tell him to upgrade if < 10 ?

(Basically let's support only > 10)

**Comment by wvffle** [comment]
>Is there something inside npm or some module to check the user node and
tell him to upgrade if < 10 ?

`"engines"` in package.json

**Comment by rom1504** [comment]
Does it do anything ?

**Comment by wvffle** [comment]
https://stackoverflow.com/a/29349773/5565538

So basically when we create .npmrc with
```
engine-strict=true
```
it should throw an error when installing. Should also work with yarn as stated in the comments

**Pull request closed without merging**
