### PR TITLE
Craft batch

### PR DESCRIPTION
**Pull request by sefirosweb**
Hi guys, to improve craft when you need to craft multiple different items in one shot, to avoid open and close the windows every time, I made a new function:

image
To:
image

Basically craft batch does same as craft but avoiding close the windows while is crafting,
This new function receive an array of recipes and the count of how many items want to craft,

Usage example:

```js
const plankRecipe = bot.recipesFor(mcData.itemsByName.oak_planks.id)[0]

    const recipes = [
      {
        recipe: plankRecipe,
        count: 2
      },
      {
        recipe: plankRecipe,
        count: 2
      },
      {
        recipe: plankRecipe,
        count: 2
      },
      {
        recipe: plankRecipe,
        count: 2
      },
      {
        recipe: plankRecipe,
        count: 2
      },
      {
        recipe: plankRecipe,
        count: 2
      },
      {
        recipe: plankRecipe,
        count: 2
      },
      {
        recipe: plankRecipe,
        count: 2
      },
      {
        recipe: plankRecipe,
        count: 2
      },
      {
        recipe: plankRecipe,
        count: 2
      },
      {
        recipe: plankRecipe,
        count: 2
      },
      {
        recipe: plankRecipe,
        count: 2
      },
      {
        recipe: plankRecipe,
        count: 2
      },
      {
        recipe: plankRecipe,
        count: 2
      }
    ]

    bot.craftBatch(recipes, craftingTable)
      .then(() => {
        console.log('Finish to craft')
      })
      .catch((e) => {
        console.log(e)
      })
```

I really think craftBatch should replace the old "craft", but this can cause compatibility problems for users,
It should be done, since having 2 functions that do similar things should not exist (it's my opinion)

I hope this simplify a bit the code of users

If you would like me to create a test for this function let me know.

### CODE REVIEW

**Comment by rom1504** [comment]
can you measure how much faster it is ?

**Comment by sefirosweb** [comment]
Hi Rom this is not much faster now with the fixes have i been did, we are talking only about of milisseconds

I request this changes to simplify the user code when want to craft multiple different recipes, 

Also I think emit windows open & close for each recipe is not correct

Best

**Comment by rom1504** [comment]
can you please add tests?

**Comment by rom1504** [comment]
@kaduvert are you interested in reviewing/finishing this ? looks similar to your interests

**Comment by kaduvert** [comment]
so i think the problem is with the craft function, which opens and closes a window from a crafting bench block

to me `bot.craft` should take a window as an argument, craft the stuff with it and not do anything more than that.

i think the user should'nt have to create an array of crafting recipes, he should just be able to call `bot.craft` with one recipe and manage the crafting bench window himself

**Comment by kaduvert** [comment]
to conclude:
i think this pr has a valid point, which is that `bot.craft` is opening and closing windows, which it shouldn't.

but i think the path to fixing this is not to implement better management of the window for the user, but giving management of the window completely to the user.

so instead of
```js
const plankRecipe = bot.recipesFor(mcData.itemsByName.oak_planks.id)[0]
const craftingTable = bot.blockAt(...)

bot.craft(plankRecipe, 2, craftingTable)
```
we should let the user obtain the window before letting him craft:
```js
const plankRecipe = bot.recipesFor(mcData.itemsByName.oak_planks.id)[0]
const craftingTable = bot.blockAt(...)

const craftingWindow = bot.activateBlock(craftingTable)

bot.craft(plankRecipe, 1, craftingWindow)

craftingWindow.close()
```

this way he can do multiple recipes and decide himself when to open or close the window

also some servers have commands like `/craft` which open a crafting window directly.
with the current implementation of `bot.craft` or the requested `bot.craftBatch` the user can not make use of this.
but he could if `bot.craft` took a window as argument

**Comment by rom1504** [comment]
makes sense to me

do you want to implement that @kaduvert ?

**Comment by kaduvert** [comment]
maybe.. ^^
let's hear from @sefirosweb on what he thinks, as he's probably most interested.

**Comment by sefirosweb** [comment]
Yes for me have more sense too, 

I would like to help to implement them but right now I'm with other work projects :(

**Pull request closed without merging**
