### PR TITLE
Add options to accept textures pack

### PR DESCRIPTION
**Pull request by DrMoraschi**
Should close this:
https://github.com/PrismarineJS/mineflayer/issues/1888

### CODE REVIEW

**Comment by u9g** [comment]
you didnt really cover allowing to download the texture pack or allowing rejecting the texture pack

**Comment by DrMoraschi** [comment]
> you didnt really cover allowing to download the texture pack or allowing rejecting the texture pack

Should I add it as a function? Or some events?

**Comment by u9g** [comment]
> > you didnt really cover allowing to download the texture pack or allowing rejecting the texture pack
> 
> Should I add it as a function? Or some events?

in my mind this is how it would work: 
```js
bot.on('resourcepack', data => bot.[accept/reject]Texturepack(data))
```

im not so sure if blindly accepting / rejecting all tpacks is the best idea

**Comment by DrMoraschi** [comment]
> > > you didnt really cover allowing to download the texture pack or allowing rejecting the texture pack
> > 
> > 
> > Should I add it as a function? Or some events?
> 
> in my mind this is how it would work:
> 
> ```js
> bot.on('resourcepack', data => bot.[accept/reject]Texturepack(data))
> ```
> 
> im not so sure if blindly accepting / rejecting all tpacks is the best idea

You're right

**Pull request closed without merging**
