### PR TITLE
Add a spammer example

### PR DESCRIPTION
**Pull request by DrMoraschi**
Just saw a message in discord of someone asking for a spammer example

### CODE REVIEW

**Comment by DrMoraschi** [comment]
Oh welp, i don't understand

**Comment by Karang** [comment]
1) you need to run standard --fix to fix tests
2) I don't think we want to add this kind of example, there is more interesting stuff one can do using mineflayer, than spamming...

**Comment by DrMoraschi** [comment]
Fair enough

**Review by wvffle — CHANGES_REQUESTED** [review]
I don't think we should teach how to create malicious bots...

We already have a tutorial that explains the basics of javascript here: https://github.com/PrismarineJS/mineflayer/blob/master/docs/tutorial.md

It's lacking setInterval; you could add it. Then a person asking how to create such bot wouldn't have any questions after reading this guide.

**Pull request closed without merging**
