### PR TITLE
explicitely use last version of protodef and nmp to get compiler speed up

### PR DESCRIPTION
**Pull request by rom1504**
cc @Karang

### CODE REVIEW

**Comment by rom1504** [comment]
Seems that is doesn't work. We'll need to fix as this is released

**Comment by rom1504** [comment]
I'll probably release a mineflayer fixing to previous version of node-minecraft-protocol in the mean time

**Comment by Karang** [comment]
> Seems that is doesn't work. We'll need to fix as this is released

Ok I'll have a look

**Comment by rom1504** [comment]
it's fixed, thanks

**Pull request merged**
