### PR TITLE
simplify chat plugin

### PR DESCRIPTION
**Pull request by plexigras**
its a quiet radical change so there might be side effects i don't know of

### CODE REVIEW

**Comment by rom1504** [comment]
Well well...
AFAIK chat is broken in 99% of real uses (ie people always come complaining it doesn't work)
I believe we should setup some automatic testing for chat for 
* spigot
* paper
* a selection of real servers out there

Testing would just be "check we can decode pseudo/message"

At least this PR doesn't break for 1.7 to 1.12 according to our tests.

Are you sure it's not needed for other servers ?

**Comment by plexigras** [comment]
i don't know of any special packages that cant be parsed by the chat message plugin but if there are it would definitly cause problems

**Comment by plexigras** [comment]
lets hope for the best

**Comment by rom1504** [comment]
yeah, it's better if it's simpler anyway, easier to fix

**Comment by Corgano** [comment]
Could we get an updated example now? How do we add custom patterns as we did before? I keep getting TypeError: bot.chatAddPattern is not a function when i run the included mineflayer example

**Comment by plexigras** [comment]
this is not due to this pr but due to async plugin injection.

you can do

```js
bot.once('inject_allowed', () => bot.chatAddPattern(...))
```

or

```js
bot.loadPlugin(() => bot.chatAddPattern(...))
```

you should open an issue if you found an issue.

**Pull request merged**
