### PR TITLE
Add nameOnTablist() on player object

### PR DESCRIPTION
**Pull request by u9g**
allows for getting a chatmessage object of the player's name like it shows on the tablist (if it shows on the tablist)

### CODE REVIEW

**Comment by IceTank** [comment]
Maybe name the property something like getNameOnTablist to indicate that it is a function and not a variable.

**Comment by u9g** [comment]
> Maybe name the property something like getNameOnTablist to indicate that it is a function and not a variable.

It's now a readonly getter

**Comment by IceTank** [comment]
Can you run the doctoc command to update the automated api.md formating? The command is also listed at the end of CONTRIBUTING.md

**Comment by IceTank** [comment]
Looks like the failing test is due to some other issue and not related to the implemented feature. Having a test for this feature would be nice too.

**Comment by rom1504** [comment]
conflicts

**Comment by rom1504** [comment]
old and not quite right, closing
please re-open if you want to finish it

**Pull request closed without merging**
