### PR TITLE
Update lib/ and test/ to use prismarine-registry

### PR DESCRIPTION
**Pull request by extremeheat**

### CODE REVIEW

**Comment by rom1504** [comment]
can you add bot.registry to the doc?

**Comment by rom1504** [comment]
There's a merge conflict

**Comment by rom1504** [comment]
LGTM but examples will need to be updated similarly

**Comment by rom1504** [comment]
Could be another PR

**Comment by extremeheat** [comment]
Yeah, I didn't update the examples here for the time being to avoid confusion with some things taking/not taking the registry

**Comment by rom1504** [comment]
ok

**Comment by rom1504** [comment]
I updated https://github.com/PrismarineJS/mineflayer/issues/2450
let's get this migration finished

**Pull request merged**
