### PR TITLE
changed resource pack example

### PR DESCRIPTION
**Pull request by U5B**
added that hash is needed for 1.9 and below

added more examples

### CODE REVIEW

**Comment by KaffinPX** [comment]
LGTM

**Comment by u9g** [comment]
at this point should we just add it as a plugin?

**Comment by KaffinPX** [comment]
I think its enough

**Review by rom1504 — CHANGES_REQUESTED** [review]
I don't think we should have examples in mineflayer telling people to use packets directly

this should be added as mineflayer methods and events

**Comment by rom1504** [comment]
now directly in mineflayer

**Pull request closed without merging**
