### PR TITLE
fixed a link in the FAQ

### PR DESCRIPTION
**Pull request by satyamedh**
fixed a link in the FAQ
very minor but took 2 minutes off my day :D

### CODE REVIEW

**Review by u9g — APPROVED** [review]
LGTM

**Comment by satyamedh** [comment]
sorry if I didnt mark this PR as something et etc
just tell me and I will do it next time :)

**Comment by Hazuki-san** [comment]
real

**Comment by satyamedh** [comment]
@Hazuki-san I honestly have no idea what you mean

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
