### PR TITLE
Add getControlState to physics

### PR DESCRIPTION
**Pull request by Camezza**

### CODE REVIEW

**Comment by u9g** [comment]
needs lint + non of the filesystem files

**Comment by Camezza** [comment]
> needs lint + non of the filesystem files

what do you mean?

**Comment by Moondarker** [comment]
See if `npm run fix` makes it any better, and all the `.DS(whatever)` files shouldn't be there :)

**Comment by Camezza** [comment]
Ah okay, thank you

**Comment by rom1504** [comment]
We already have bot.controlState

Ways to go here:
1. Do nothing and close
2. Update setControlState doc to mention controlState
3. Add your getControlState to doc

Up to you

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
