### PR TITLE
Wait between clicks option

### PR DESCRIPTION
**Pull request by IceTank**

### CODE REVIEW

**Comment by IceTank** [comment]
This pr adds the option to wait between clicks in the mineflayer api. This should help with servers that are lagging or have high ping.

**Comment by u9g** [comment]
imo waiting between clicks should be opt-in, not opt-out

**Comment by IceTank** [comment]
> imo waiting between clicks should be opt-in, not opt-out

Were is it not opt-in? Also I just realized that this will break any legacy code that uses callbacks. So this might have to wait until callbacks are removed.

**Comment by rom1504** [comment]
I do not understand the purpose of this PR
why would you want to make your bot slow ?

**Pull request closed without merging**
