### PR TITLE
Adding more click types

### PR DESCRIPTION
**Pull request by KadaverBrutalo10**
https://github.com/PrismarineJS/prismarine-windows/pull/29

### CODE REVIEW

**Comment by u9g** [comment]
How far along is this? What still needs to be done?

**Comment by KadaverBrutalo10** [comment]
i don't know if you are asking me but practially i don't see a reason for this to take so long, while i haven't tested my changes against every edge case the basics and beyond are covered. i'm currently working on automating the testing of these clicks to maybe get things going, but i'm more passively working on that and it's more of a making others believe that my changes work instead of finding bugs myself.
As i said days ago in my initial statement about these changes: there are things unimplemented (as being able to put things where they should not be) but this has to be done with intent, meaning you have to mouse click drag for example a stone on the helmet slot in the inventory, also this was not - as i said - included in previous versions and can be done by someone else if the motivation is there. this serves more of basic fundament of the main click modes.

The only thing however that is lacking implementation because i'm not the best in this PrismarineJS ecosystem is in my prismarine-windows PR in file /lib/Window.js at line 121 a check if the version is newer or equal to 1.9 needs to be made to correctly implement a "number click" in versions above 1.8
This is the only thing i can't do with much certainty and i would be thankful if someone could do that, it's no big deal but i don't want to create an imperfect implementation that me seem unclean or smth along these lines to a long contributor to this project.

I cannot guarantee 100% coverage of my changes but the cases i can think of are tested manually and kind of automatically by me.
You are highly encouraged to search along and report these bugs to me and i will fix them!

Thank You.

**Comment by rom1504** [comment]
commented at https://github.com/PrismarineJS/prismarine-windows/pull/29

with no test, this is really complex and likely to come bit us if I just merge

**Comment by rom1504** [comment]
this will probably be closed soon

**Comment by rom1504** [comment]
closing due to absence of tests
https://github.com/PrismarineJS/mineflayer/issues/271#issuecomment-899045650 tracked there if someone want to finish it someday

**Pull request closed without merging**
