### PR TITLE
Mineflayer TypeScript definitions

### PR DESCRIPTION
**Pull request by IdanHo**
I documented all functions listed in the docs. Unfortunately quite a lot of the prismarine-* packages are missing typescript definitions, and as such, i used `object`s as placeholders, any missing type is annotated like this:
`object /*prismarine-package Type*/`
This should not be merged until the missing types are added to the appropriate repositories and the placeholders and replaced.

### Currently missing types:
- [x] prismarine-entity Entity
- [x] prismarine-block Block
- [x] prismarine-biome Biome
- [x] prismarine-windows Window
- [x] prismarine-item Item
- [x] prismarine-recipe Recipe
- [x] vec3 Vec3

### CODE REVIEW

**Comment by rom1504** [comment]
all dependencies released, please update

**Comment by rom1504** [comment]
do you know if it's possible to automatically check whether these type definitions match the js code ?

**Comment by IdanHo** [comment]
Pretty sure the only way is to convert mineflayer's tests to ts, but instead of checking for intended behaviour, checking it doesn't crash with a type mismatch error

**Comment by rom1504** [comment]
ok let's merge it
since it's not automatically checked by anything, they may be discrepancies that creep up with actual code in the future, but I guess it's not that of a big deal since it's just IDE help, we can fix it when we notice

**Pull request merged**
