### PR TITLE
Add autoreconnect

### PR DESCRIPTION
**Pull request by CyberPatrick**
The solution of task https://github.com/orgs/PrismarineJS/projects/11#card-44565850

### CODE REVIEW

**Comment by DrMoraschi** [comment]
Would this bind events? For example if you have a bot.on "chat" event, would it work after reconnect?

**Comment by CyberPatrick** [comment]
> Would this bind events? For example if you have a bot.on "chat" event, would it work after reconnect?

Hmm, no.

**Comment by DrMoraschi** [comment]
So... What do we do?

**Review by aesthetic0001 — COMMENTED** [review]
I don't see the benefit of this when you could just createBot again (especially since it doesn't bind events)

**Pull request closed without merging**
