### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by gkal19**

### CODE REVIEW

**Comment by rom1504** [comment]
why did you close the PR ?
These might be interesting changes

**Comment by plexigras** [comment]
yeah i think we should updated the repo to use es6 but we should make it so its backwards compatible using babel.

while doing that we should also add a .eslintrc and an maybe a .editorconfig file.

**Comment by rom1504** [comment]
We decided to just use es6 in node-minecraft-protocol and drop babel.
I think we can do that here too.
See https://github.com/PrismarineJS/node-minecraft-protocol/pull/319

**Comment by plexigras** [comment]
oh ok then no babel then

**Pull request closed without merging**
