### PR TITLE
1.21

### PR DESCRIPTION
**Pull request by Madlykeanu**

### CODE REVIEW

**Comment by Madlykeanu** [comment]
chat works but its recieving it differently for some reason in 1.21
image

**Comment by rom1504** [comment]
Mojang usually breaks things for no reason.

Add a feature in mcdata to distinguish

**Comment by SuperGamerTron** [comment]
Looks like the chat types got incremented in the newest protocol version for whatever reason.
image
I was able to fix it with this: SuperGamerTron/prismarine-registry@6d2e1ca73bf8077b22987dbc183424a527f82862

**Comment by rom1504** [comment]
Please open a PR

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-registry/pull/42

**Comment by rom1504** [comment]
Chat test fixed

**Comment by rom1504** [comment]
Failing at consume now with this

TypeError: SizeOf error for undefined : Cannot read properties of undefined (reading 'x')
    at Object.vec2f (eval at compile (/home/runner/work/mineflayer/mineflayer/node_modules/protodef/src/compiler.js:262:12), <anonymous>:83:21)
    at Object.packet_use_item (eval at compile (/home/runner/work/mineflayer/mineflayer/node_modules/protodef/src/compiler.js:262:12), <anonymous>:2308:26)
    at eval (eval at compile (/home/runner/work/mineflayer/mineflayer/node_modules/protodef/src/compiler.js:262:12), <anonymous>:2376:56)
    at packet (eval at compile (/home/runner/work/mineflayer/mineflayer/node_modules/protodef/src/compiler.js:262:12), <anonymous>:2379:9)
    at CompiledProtodef.sizeOf (/home/runner/work/mineflayer/mineflayer/node_modules/protodef/src/compiler.js:89:14)
    at e.message (/home/runner/work/mineflayer/mineflayer/node_modules/protodef/src/compiler.js:96:40)
    at tryCatch (/home/runner/work/mineflayer/mineflayer/node_modules/protodef/src/utils.js:50:16)
    at CompiledProtodef.createPacketBuffer (/home/runner/work/mineflayer/mineflayer/node_modules/protodef/src/compiler.js:96:20)
    at Serializer.createPacketBuffer

Seems like wrong packet definition

**Comment by rom1504** [comment]
so the problem is pchat toString is producing "* flatbot hello" instead of "<flatbot> hello" which makes the test get stuck

**Comment by rom1504** [comment]
fixed that; we're now at fishing test

**Comment by rom1504** [comment]
I merged and released most deps

I left some comments in nmp and mcdata prs; would be nice to look into it so we can merge those too

**Comment by rom1504** [comment]
all external tests working

now only internal tests to fix

**Comment by rom1504** [comment]
now all passing but there seems to be a weird regression only in 1.19.2 https://github.com/PrismarineJS/mineflayer/actions/runs/11534777950/job/32109169450

**Comment by rom1504** [comment]
I do not reproduce any failure in 1.19.2 locally

**Comment by rom1504** [comment]
rerunning fixes it; something flaky

**Comment by rom1504** [comment]
tested jumper digger inventory manually, it works

**Pull request merged**
