### PR TITLE
Allow opening of smoker/blast furnace

### PR DESCRIPTION
**Pull request by ArcticZeroo**
This PR adds the ability to use `bot.openFurnace` on the smoker and blast furnace type furnaces. This currently does not validate items being put into their correct furnaces (e.g. only food into the smoker, only ores into the blast furnace), but that seems to be the case for the base furnace as well.

External tests also now test for the ability to open all types of furnaces rather than just the base furnace. 

I also noticed that tasks could be cancelled more than once, and if task.finish is called after task.cancel, the promise will throw an error because it has already rejected. This is now not possible behavior.

This PR is "complete", but I was unable to run local tests on my windows machine, so I can't verify whether the changes to the test work.

### CODE REVIEW

**Comment by rom1504** [comment]
tests are not passing

**Comment by ph0t0shop** [comment]
Just to link them, this would fix #1526.

**Comment by ArcticZeroo** [comment]
Oh whoops, totally forgot to link to the issue, thanks @ph0t0shop 

Regarding the tests, @TheDudeFromCI I was seeing a bunch of errors both locally and on gitpod that rom thought may have been due to an incorrect java version. When I get a some free time, I will see if  I can get local tests to start running and diagnose the issue.

**Comment by ArcticZeroo** [comment]
FYI, waiting for https://github.com/PrismarineJS/mineflayer/pull/1586/ to land until I look into these test failures

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/pull/1586 is now merged, please rebase

**Comment by Karang** [comment]
done in #1640

**Pull request closed without merging**
