### PR TITLE
Add physicsTick documentation

### PR DESCRIPTION
**Pull request by U5B**
Let me know if the description should be edited.

### CODE REVIEW

**Comment by u9g** [comment]
LGTM

**Comment by KaffinPX** [comment]
Dont merge we need tests.

**Review by extremeheat — APPROVED** [review]

**Comment by U5B** [comment]
> Dont merge we need tests.

It passes current tests so it is fine :D

**Comment by KaffinPX** [comment]
Lol merge it @rom1504

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
