### PR TITLE
Fixed entityAttach and entityDetach events.

### PR DESCRIPTION
**Pull request by LetsChill**
Since all non-player entities can be ridden, this pull request makes it easy to access what rides entities and when does an entity ride another entity or a vehicle.

if this feature is good enough, [prismarine-entity](https://github.com/PrismarineJS/prismarine-entity) should also be updated to add the .passengers attribute.

it has been tested and the events are working as intended.

Fix for #2819

### CODE REVIEW

**Comment by rom1504** [comment]
tests are failing

**Comment by LetsChill** [comment]
Nothing related to my changes. It appears that it happens not only for me, but for multiple people.

**Comment by LetsChill** [comment]
There is an issue that I discovered. On 1.8.9, the event gets repeated endlessly, I think set_passengers is fired even though passengers has already been assigned.

**Comment by rom1504** [comment]
can you rebase on master?

**Comment by rom1504** [comment]
please re-open if you want to finish it

**Pull request closed without merging**
