### PR TITLE
remake pviewer in tests pr

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Comment by u9g** [comment]
it works... a bit? seems like some of the videos corrupted when downloading? odd...

**Comment by rom1504** [comment]
that's cool but idk if we can afford to have 1GB of artifact for each commit
what do you think ? should we merge ?

**Comment by rom1504** [comment]
cool but let's not do it

**Comment by rom1504** [comment]
or maybe we can add an option somewhere to enable it only if needed ?

**Comment by u9g** [comment]
> or maybe we can add an option somewhere to enable it only if needed ?

maybe lets wait for player models to land

**Comment by rom1504** [comment]
old

**Pull request closed without merging**
