### PR TITLE
Added 3rd party state machine plugin link.

### PR DESCRIPTION
**Pull request by TheDudeFromCI**
Wrote a simple plugin that allows for users to write bot behaviors in the form of a finite state machine. It's designed to allow bot behaviors to scale in a practical manner.

### CODE REVIEW

**Comment by wvffle** [comment]
FSM is relatively easy to implement. In my opinion a person who knows how finite state machines work should have enough knowledge to implement them. 

Many of those who will dig through the plugins and decide to try this plugin out will get confused how does it work. 

There are a bunch of modules responsible for FSM and AI in general. It's pretty easy to connect them to mineflayer. I'd rather go that way.

**Comment by Karang** [comment]
> FSM is relatively easy to implement. In my opinion a person who knows how finite state machines work should have enough knowledge to implement them.
> 
> Many of those who will dig through the plugins and decide to try this plugin out will get confused how does it work.
> 
> There are a bunch of modules responsible for FSM and AI in general. It's pretty easy to connect them to mineflayer. I'd rather go that way.
> 
> Besides your work and effort, looking at your approach, the plugin is far from done and needs a lot of time to develop

On the other hand, having something that is plug and play for mineflayer is a great opportunity to teach ai concepts to beginners.

Sure the plugin is new and can be improved, but as long as it is continued and updated, I think it is good to have it listed.

**Comment by Karang** [comment]
> I plan on adding many default behaviors to the plugin to give the player some high-level controls for Mineflayer. I've added a few already, idle, look at entities, and follow an entity. I will be adding many more over the next few weeks. Yeah, I probably did link the project a little too early, so I'll make sure to have the plugin presentable as soon as possible.

You can also link it in https://github.com/PrismarineJS/mineflayer/issues/981 ;)

**Comment by wvffle** [comment]
> @rom1504 Yeah I will. I'll keep this PR open until the plugin is more user friendly and overall more presentable. I got excited and made this PR too early, lol

I'll convert it to draft then.

**Pull request merged**
