### PR TITLE
1.19.4

### PR DESCRIPTION
**Pull request by extremeheat**
After https://github.com/PrismarineJS/minecraft-data/pull/710

Fixed
```js
  46 passing (3m)
  1 failing

  1) mineflayer_external 1.19.4
       bed:
     Error: bot is not sleeping
      at Timeout._onTimeout (lib/plugins/bed.js:158:16)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

### CODE REVIEW

**Comment by rom1504** [comment]
1) mineflayer_external 1.19.4
       bed:
     Error: bot is not sleeping

still

**Comment by kerkkoh** [comment]
Bump. Both protocol and data packages have been updated. Can't wait to see this done <3

**Comment by rom1504** [comment]
Bump doesn't help

Finding the issue with bed would

**Comment by rom1504** [comment]
thanks

**Pull request merged**
