### PR TITLE
Updated how awaitMessage works.

### PR DESCRIPTION
**Pull request by QimieGames**
Just for my conveniences, not even going to lie about it.

### CODE REVIEW

**Comment by amoraschi** [comment]
In this case I think timeout should be the first argument since rest parameters must be last

**Comment by QimieGames** [comment]
> In this case I think timeout should be the first argument since rest parameters must be last

Done. Check the latest commit. Felt like im missing something still. Ill try to look more. Ill tell ya when im done. https://github.com/PrismarineJS/mineflayer/pull/2718/commits

**Comment by QimieGames** [comment]
Yeah im done with everything. Pretty sure anyways (except other languages cause I can only understand English and my native lang). Have fun reviewing and thanks! <3

**Comment by QimieGames** [comment]
Making awaitMessage async also allows user to run commands in chat after awaitMessage has been executed. Instead of running the command before or using setTimeout to run the command for example /stats or any commands that needs the player to run a command before giving output in chat. (My main intention of this whole PR xD)

**Comment by rom1504** [comment]
this is breaking, can you instead make a new function ?

**Comment by QimieGames** [comment]
> this is breaking, can you instead make a new function ?

Im new to all this stuff but I will try my best.

**Pull request closed without merging**
