### PR TITLE
1.18 support

### PR DESCRIPTION
**Pull request by rom1504**
needs
* [x] pchunk update
* [x] block/items data in mc data
* [x] update in mineflayer code
* [x] checking p* packages still work
* [x] material.json 1.18
* [x] https://wiki.vg/index.php?title=Pre-release_protocol&oldid=17160 for identifying next steps
* [x] check a bunch of examples manually

for another PR:
* biomes dynamic support (see work at https://github.com/PrismarineJS/prismarine-registry/issues https://github.com/PrismarineJS/prismarine-chunk/pull/162)

### CODE REVIEW

**Comment by littlefryingpan** [comment]
Is there already effort on going for these four tasks? If not, I will try and contribute

**Comment by catfishjw** [comment]
I am currently working on step 2 (block/item data), should be done in a bit

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-chunk/issues/154 or https://github.com/PrismarineJS/prismarine-chunk/issues/153 will help fix find block

**Comment by rom1504** [comment]
the choices for materials are
1. https://github.com/Archengius/minecraft-data-generator/blob/master/src/main/java/me/arch/mcdatagen/generators/MaterialsDataGenerator.java
2. https://github.com/PrismarineJS/burger-extractor + https://github.com/mcdevs/burger
3. https://github.com/PrismarineJS/minecraft-wiki-extractor/blob/master/lib/block_extractor.js#L322 / manually writing the file

choice 2 would be the cleanest, 1 or 3 probably the quickest but not easy to reuse in 1.19

**Comment by rom1504** [comment]
the burger path may require to redefine the definition of material / define a new field in blocks.json like "base dig time"
the goal of materials is only to get <https://github.com/PrismarineJS/prismarine-block/blob/master/index.js#L266> to work
any alternative property is fine as long as we can backport it to older versions

**Comment by rom1504** [comment]
materials.json solved

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-chunk/issues/157

**Comment by rom1504** [comment]
https://wiki.vg/index.php?title=Pre-release_protocol&oldid=17160 for identifying next steps

**Comment by rom1504** [comment]
failing blockAt internal test just needs a fix of https://github.com/PrismarineJS/mineflayer/blob/master/test/internalTest.js#L131

**Review by EndermanHackerVN — APPROVED** [review]

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/tree/1_18#example doc on how to running specific tests

for example `npm run mocha_test -- -g "1.18.*BlockFinder"`

**Comment by rom1504** [comment]
npm run mocha_test -- -g "mineflayer_internal 1.18.*blockAt"

```
  mineflayer_internal 1.18
Error: Attempted to read beyond the bounds of the managed data.
    at SmartBuffer.ensureReadable (/workspace/mineflayer/node_modules/smart-buffer/build/smartbuffer.js:1093:19)
    at SmartBuffer._readNumberValue (/workspace/mineflayer/node_modules/smart-buffer/build/smartbuffer.js:1163:14)
    at SmartBuffer.readInt16BE (/workspace/mineflayer/node_modules/smart-buffer/build/smartbuffer.js:118:21)
    at Function.read (/workspace/mineflayer/node_modules/prismarine-chunk/src/pc/common/PaletteChunkSection.js:78:41)
    at ChunkColumn.load (/workspace/mineflayer/node_modules/prismarine-chunk/src/pc/1.18/ChunkColumn.js:242:41)
    ```

looking into internal tests

**Comment by rom1504** [comment]
for beds we need the new /setblock command to update 
```
    bot.chat(`/setblock ${bedPos1.toArray().join(' ')} ${bedItem.name}[part=foot]`)
    bot.chat(`/setblock ${bedPos2.toArray().join(' ')} ${bedItem.name}[part=head]`)
```
if someone can boot minecraft and tell me what it is, it'll be appreciated

**Comment by Beaness** [comment]
It seems like that the beds got placed correctly. However the multi block change packet seems not to be handled correctly. Is this y level normal?
```
multi_block_change {
  chunkCoordinates: { x: 0, z: 0, y: 1048572 },
  notTrustEdges: false,
  records: [ 4436500, 4440580 ]
}
```

**Comment by rom1504** [comment]
now test pass so the next step is https://github.com/PrismarineJS/prismarine-chunk/pull/162 (and some more in mineflayer) for biome dynamic support

then testing a bunch of example: calling volunteers on this one

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/pull/2110#issuecomment-903341087

**Comment by rom1504** [comment]
* [ ] inventory.js
* [ ] chest.js
* [ ] digger.js
* [ ] jumper.js

**Pull request merged**
