### PR TITLE
added book writing plugin

### PR DESCRIPTION
**Pull request by plexigras**
requested by @oxygenecore #482

### CODE REVIEW

**Comment by rom1504** [comment]
hmm so why did you create a new PR ?

**Comment by roblabla** [comment]
It'd be nice to have some tests, I think. Otherwise, looks great :).

**Comment by rom1504** [comment]
Yeah as I said in https://github.com/PrismarineJS/mineflayer/pull/489#issuecomment-281137532 , it would be nice to add an example on how to use this ;)
It's also useful to test (manually) that it works ;) (and still works on updates)

**Comment by plexigras** [comment]
**this is what i used for testing purposes:**

```js
var pages = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
  'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
].map(page => {
  return page
    .split(' ')
    .map((word, i) => `§${(i%13+1).toString(16)}${i%2?'§l':''}${word}`)
    .join(' ')
})

bot.once('login', () => console.log('loged in'))
bot._client.once('window_items', () => {
  console.log('got items');
  print();
  var [ book ] = bot.inventory.items().filter(({ name }) => name === 'writable_book')
  bot.writeBook(book.slot, pages, () => {
    print();
    bot.quit();
  });
});

function print() {
  var books = bot.inventory.items().filter(({ name }) => name === 'writable_book')
  console.log('books:',books.length);
  console.log('slots:',books.map(book => book.slot));
}
```

**Comment by rom1504** [comment]
merged in 484ada26f8a89a1a7a4c467faaf34b95251e35a1 , thanks @plexigras !

**Pull request closed without merging**
