### PR TITLE
Fix 'Fishing cancelled due to calling bot.fish() again' when calling bot.fish() inside the callback

### PR DESCRIPTION
**Pull request by GroobleDierne**
I've tested, there's no such problem for bot.consume()

### CODE REVIEW

**Comment by GroobleDierne** [comment]
I forgot the npm run fix :/

**Comment by IdanHo** [comment]
Just do it and add another commit called formatting :) also suggest adding the words "closes #1217" to make it auto close your issue once this pull request gets merged

**Comment by Karang** [comment]
> I've tested, there's no such problem for bot.consume()

Indeed, consume use setImmediate so the cb is effectively called when the function returns (and thus after lastEating is reset to undefined)
```js
lastEating = (err) => setImmediate(cb, err)
```

Can you reset lastFloat also before calling the callback ? (for consistency)

**Comment by GroobleDierne** [comment]
I'm currently waiting for the end of npm install ^^

**Comment by rom1504** [comment]
Why did you close it ?!

**Comment by GroobleDierne** [comment]
It was an error sorry

**Pull request merged**
