### PR TITLE
adding new feature activateEntityWithOptions

### PR DESCRIPTION
**Pull request by Katzengott**
v1

### CODE REVIEW

**Comment by amoraschi** [comment]
Lint is failing

You also should add it to api.md and index.d.ts

**Comment by IceTank** [comment]
Maybe also add the option to control the sneaking and hand parameter? Also that is not a valid index.d.ts entry. It should be something like `activateEntityWithOptions: (block: Entity, position: Vec3, mouse: 0 | 1) => Promise<void>`

**Comment by Katzengott** [comment]
ok Where should I run npm run fix

**Comment by IceTank** [comment]
> ok Where should I run npm run fix

In the project root directory where you also run `npm install` to install mineflayer dependencies

**Comment by Katzengott** [comment]
Somehow that doesn't work for me. I'm just too stupid to do it right

**Comment by IceTank** [comment]
> Somehow that doesn't work for me. I'm just too stupid to do it right

go to #help in the discord

**Comment by Katzengott** [comment]
It looks good

**Comment by rom1504** [comment]
Why not instead add options to the existing function?

**Comment by Katzengott** [comment]
Would also go. I can also change it again. I thought it looks better

**Comment by IceTank** [comment]
It is better to have one function that is as flexible as possible then to have multiple different functions doing almost the same stuff. You can add something like this
```js
activateEntityWithOptions(entity: Entity, options: { position?: Vec3, mouse?: 0 | 1, sneak?: boolean,  hand?: 'right' | 'left' })
```
and then make those options optional. Once you have this you can also refactor activateEntity to use activateEntityWithOptions. If you refactor it you make sure that there is only one place in mineflayer where it has to write the raw packet information making it easier in the future to update the packet.

**Comment by rom1504** [comment]
old

**Pull request closed without merging**
