### PR TITLE
Add nbt option to withdraw and deposit

### PR DESCRIPTION
**Pull request by IceTank**
Exposes options for withdraw in containers and adds an extra matcher function. 
Allows for withdrawing items with specific nbt tags.

### CODE REVIEW

**Review by rom1504 — CHANGES_REQUESTED** [review]
could you instead change deposit and withdraw ?
this pattern of duplicating methods is not good, we should remove it for place with options

**Comment by IceTank** [comment]
I don't quit understand what you mean. Should I rename the function or replace withdraw and deposit with my functions? Just replacing them would make it a breaking change.

**Comment by rom1504** [comment]
I think you should change the existing functions to add the parameters you want without making a breaking change

**Comment by rom1504** [comment]
afraid this would be breaking due to callbacks
let's wait a little that we remove the callbacks

**Comment by IceTank** [comment]
Is there a time frame for removing callbacks?

**Comment by rom1504** [comment]
yes, whenever someone does #1482 ; I think it would be great to do ASAP

**Comment by rom1504** [comment]
Can you now rebase this on master @IceTank ? Should be possible now that we removed callbacks

**Pull request merged**
