### PR TITLE
Initial 1.20.2 support

### PR DESCRIPTION
**Pull request by crux153**
This PR adds preliminary support for version 1.20.2.

Before merging this PR, we need PrismarineJS/prismarine-nbt#78 and PrismarineJS/node-minecraft-protocol#1264 to be merged and released.

I have tested that a bot can successfully log in to an offline server and interact with chunks using this patch. But I believe additional testing is necessary.

### CODE REVIEW

**Comment by rom1504** [comment]
can you

- add the new version in the tested versions to trigger tests
- update the version towards the open PRs for the changed deps

**Comment by rom1504** [comment]
added the version in tested version

some things needed here:
* use playerJoin event instead of login
* check against new things in https://github.com/PrismarineJS/node-minecraft-protocol/pull/1265

**Comment by rom1504** [comment]
https://minecraft.fandom.com/wiki/Java_Edition_1.20 references of new things

https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.20.2/protocol.json to diff against https://github.com/PrismarineJS/minecraft-data/blob/master/data/pc/1.20.1/protocol.json

tasks here
* list things that need update here
* do it here and potentially in sub packages (pchunk ?)
* make tests work
* test a few examples manually

**Comment by rom1504** [comment]
Fixed

**Comment by wgaylord** [comment]
Adding this into the block.js in mineflayer adds support for the chunk batch system. Normally MC clients average the last 15 chunk batches but I think we can get away with not doing that.
```
var chunkBatchStartTime = 0
  bot._client.on('chunk_batch_start', (packet) => {
    chunkBatchStartTime = Date.now()
  })
  
  bot._client.on('chunk_batch_finished', (packet) => {
    var chunkPerMili = packet.batchSize / (Date.now() - chunkBatchStartTime)
    bot._client.write('chunk_batch_received', {
      chunksPerTick: 25 / chunkPerMili
    })
  })
```

**Comment by rom1504** [comment]
moving to https://github.com/PrismarineJS/mineflayer/pull/3262 to make things easier to contribute to

**Pull request closed without merging**
