### PR TITLE
allow passing nmpclient as an object in createbot

### PR DESCRIPTION
**Pull request by u9g**
instead of always creating it in mf, allow for it to be passed

### CODE REVIEW

**Review by rom1504 — CHANGES_REQUESTED** [review]
why ?

doc should be updated

**Comment by u9g** [comment]
added, it is discussed here why https://discord.com/channels/413438066984747026/743199746876768318/826696291668721664

**Comment by rom1504** [comment]
ok can you put a short explanation about that use case in the api.md line ? (maybe say it can be used for a proxy + mineflayer use case)

**Comment by u9g** [comment]
added

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
