### PR TITLE
Add auth-auth plugin

### PR DESCRIPTION
**Pull request by G07cha**
Small plugin that allows to login/register as bot in servers that using chat authentication system.

### CODE REVIEW

**Comment by rom1504** [comment]
Did you try it ? Does it work ?

I can't see any bot.chat in your code so I don't understand.

**Comment by pokeball99** [comment]
@rom1504 i don't think this belongs into this repo

**Comment by rom1504** [comment]
@pokeball99 it's a plugin ! (the code is not in mineflayer repo)
So that's okay.

But still, better check it works before putting it in mineflayer readme.

**Comment by G07cha** [comment]
@rom1504 you are absolutely correct. I've rewritten prototype and forgot to add `bot.chat`. It's fixed in latest version(0.0.2). This is a big shame for me.

**Pull request merged**
