### PR TITLE
Add and revise simplified Chinese language documents

### PR DESCRIPTION
**Pull request by AdminHcat**
Add and revise simplified Chinese language documents

添加修订了一些简体中文语言文档

### CODE REVIEW

**Comment by extremeheat** [comment]
Run to fix lint:

 npx standard-markdown docs/ --fix

**Comment by AdminHcat** [comment]
> Run to fix lint:
> 
> npx standard-markdown docs/ --fix

Tried to run but no files changed

**Comment by extremeheat** [comment]
You're right, the package seems broken/dead per https://github.com/zeke/standard-markdown/issues/23 and https://github.com/zeke/standard-markdown/pull/29

try running :
```
npx abetomo/standard-markdown#fix_fix_option_not_executed docs/ --fix
```

**Comment by Nyaasu66** [comment]
> Add and revise simplified Chinese language documents
> 
> 添加修订了一些简体中文语言文档

Good Job !
你做得好啊（ ᕕ( ᐛ )ᕗ
|∀` )

**Pull request merged**
