### PR TITLE
Add code snippets

### PR DESCRIPTION
**Pull request by u9g**

### CODE REVIEW

**Review by wvffle — COMMENTED** [review]
Honestly I see no point in supporting snippets in the library. There are many  different snippet formats and many different editors besides vscode. In my opinion this should be an external plugin.

**Comment by u9g** [comment]
> Honestly I see no point in supporting snippets in the library. There are many different snippet formats and many different editors besides vscode. In my opinion this should be an external plugin.

Why? VSCode is by far the most used IDE from contributors, it's just a nice productivity boost

**Review by DrMoraschi — CHANGES_REQUESTED** [review]
On L8 it should be mineflayer-createbot* right?

**Comment by u9g** [comment]
> On L8 it should be mineflayer-createbot* right?

fixed

**Comment by wvffle** [comment]
> > Honestly I see no point in supporting snippets in the library. There are many different snippet formats and many different editors besides vscode. In my opinion this should be an external plugin.
> 
> Why? VSCode is by far the most used IDE from contributors, it's just a nice productivity boost

Are those snippets for contributors or for end users? Judging from the changes, for the latter.

Correct me if I am wrong but I just do not see the point of adding those type of files as a part of a library. How would it be distributed? With an npm module? I can see many in-production instances bloated by it. So adding it to the npmignore would be a must in my opinion. Then what? Shipping it with `git clone`? That doesn't make any sense as well. As I said before, those snippets you proposed are mostly for the end users who would have mineflayer installed as a dependency..
 
The best solution in my opinion (though I have no idea how it is done in VS Code) is to create a VS Code addon/plugin (if it even allows such things) or do it in external library that would add all of the snippets. 

Actually I'd also move the typescript typings to an external library as well.

**Comment by rom1504** [comment]
There is no "bloating the npm package" issue. Going from 3.5kB to 3.8kB will cause no issue.

**Comment by rom1504** [comment]
Status here ?

**Comment by rom1504** [comment]
reopen if you want to work on it again

**Pull request closed without merging**
