### PR TITLE
Update

### PR DESCRIPTION
**Pull request by Justman100**

### CODE REVIEW

**Comment by Justman100** [comment]
@vicdum

**Comment by extremeheat** [comment]
The deps are not pinned, so they will update themselves, this PR is not needed. I don't understand the rationale for the other changes.

**Comment by Justman100** [comment]
> The deps are not pinned, so they will update themselves, this PR is not needed. I don't understand the rationale for the other changes.

ARE YOU KIDDING ME? WHERE DO THEY UPDATE THEMSELVES? AND STOP FUCKING WASTING OTHER PEOPLE'S WORK AND TIME! TALK FIRST, THEN DECIDE! FUCK THIS OFF SLOWLY! INSTEAD OF JUST ASKING FOR DETAILS!

THEN RULE THE SHIT YOURSELF! WON'T DO ANYTHING MORE HERE! JUST SAD THAT SUCH ASSHOLES ARE MAINTAINERS

**Comment by AnyBananaGAME** [comment]
I think you need a therapy not a Contributor status

**Comment by extremeheat** [comment]
Your PR has no description beyond "Update" and makes several miscellaneous changes that aren't explained, like switching the package manager and updating github workflows. Without providing a description it's not always possible to know what the intention of the PR is, in which case you should not expect PRs to not be closed.

If your intention was to update the deps, then as written in previous PR:
> Bumping the versions here will have no effect on installs as npm uses semantic versioning and we use the ^ designator. Read https://docs.npmjs.com/about-semantic-versioning

You can re-open if you want to provide more detailed information about what you are trying to do/achieve. As github is a public place, I don't think a future employer would like to see past messages like that.

**Comment by kotinash** [comment]
> > The deps are not pinned, so they will update themselves, this PR is not needed. I don't understand the rationale for the other changes.
> 
> ARE YOU KIDDING ME? WHERE DO THEY UPDATE THEMSELVES? AND STOP FUCKING WASTING OTHER PEOPLE'S WORK AND TIME! TALK FIRST, THEN DECIDE! FUCK THIS OFF SLOWLY! INSTEAD OF JUST ASKING FOR DETAILS!
> 
> THEN RULE THE SHIT YOURSELF! WON'T DO ANYTHING MORE HERE! JUST SAD THAT SUCH ASSHOLES ARE MAINTAINERS

💀

**Pull request closed without merging**
