### PR TITLE
Default hideErrors to false

### PR DESCRIPTION
**Pull request by U5B**
Inspired by: https://discord.com/channels/413438066984747026/413438150594265099/883788843613057055

### CODE REVIEW

**Comment by rom1504** [comment]
can we instead log to a file ?
if we merge this, tomorrow there will be 10 issues about "it doesn't work, I saw a warning"

**Comment by U5B** [comment]
Where should I log the file?

**Comment by u9g** [comment]
I disagree with logging to a file because what if you have 10 mineflayer bots all logging to a single file?

**Comment by rom1504** [comment]
Indeed logging to a single file is not a good idea

**Pull request closed without merging**
