### PR TITLE
Change scope of createActionNumber

### PR DESCRIPTION
**Pull request by Camezza**
Allows for low level client window packet transactions to be made by specifying a valid actionId

### CODE REVIEW

**Comment by u9g** [comment]
Can you give an example of why something like this would need to be used?

**Comment by Camezza** [comment]
For example, clicking a window slot:

```
                this.bot._client.write('window_click', {
                    windowId: window.id,
                    slot: slot,
                    mouseButton: mouseButton
                    action: this.bot.createActionNumber(),
                    mode: 0,
                    item: { blockId: -1 },
                });
```

**Comment by u9g** [comment]
I suggest you take a look at [this](https://github.com/PrismarineJS/mineflayer/blob/master/docs/api.md#botclickwindowslot-mousebutton-mode-cb) because `bot.clickWindow(slot, mouseButton, 0)` does the same thing while having the benefit of abstraction from the raw packet.

**Comment by Camezza** [comment]
Unfortunately, this solution didn't work for me due to inability to specify windows passed from the windowOpen event

**Comment by u9g** [comment]
> Unfortunately, this solution didn't work for me due to inability to specify windows passed from the windowOpen event

this is a bug with bot.clickWindow because the opened window’s id should be entered itself

**Comment by Camezza** [comment]
Is this able to be approved? Changes are complete, now it's a case of them being accepted or rejected

**Comment by Karang** [comment]
> Is this able to be approved? Changes are complete, now it's a case of them being accepted or rejected

This PR only changes the doc, it doesn't modify the scope of the createActionNumber function. You need to modify https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/inventory.js to do so.

**Comment by Karang** [comment]
> > Unfortunately, this solution didn't work for me due to inability to specify windows passed from the windowOpen event
> 
> this is a bug with bot.clickWindow because the opened window’s id should be entered itself

To rephrase a bit what U9G said: you don't need to give clickWindow the window from the windowOpen event because it keeps track internally of what window is open. There can always be only one window open at a time, so you shouldn't ever care about specifying the id yourself.

**Comment by Camezza** [comment]
> > Is this able to be approved? Changes are complete, now it's a case of them being accepted or rejected
> 
> This PR only changes the doc, it doesn't modify the scope of the createActionNumber function. You need to modify https://github.com/PrismarineJS/mineflayer/blob/master/lib/plugins/inventory.js to do so.

Ah sorry, my mistake. It has been updated.

> > > Unfortunately, this solution didn't work for me due to inability to specify windows passed from the windowOpen event
> > 
> > 
> > this is a bug with bot.clickWindow because the opened window’s id should be entered itself
> 
> To rephrase a bit what U9G said: you don't need to give clickWindow the window from the windowOpen event because it keeps track internally of what window is open. There can always be only one window open at a time, so you shouldn't ever care about specifying the id yourself.

I'll create another PR regarding this 👍

**Review by rom1504 — APPROVED** [review]

**Comment by rom1504** [comment]
as explained above, this isn't needed

**Pull request closed without merging**
