### PR TITLE
Bye blockInSight :( 

### PR DESCRIPTION
**Pull request by KaffinPX**
Bye bye our helper. RIP

### CODE REVIEW

**Comment by rom1504** [comment]
Why

**Comment by KaffinPX** [comment]
It was deprecated, now i removed it

**Comment by rom1504** [comment]
Did you check that nothing in this repo, in plugins and in user repos is using it ?

**Comment by Hazuki-san** [comment]
I think this function should be left inside the code, even though it is outdated... but some people might be using it.

**Pull request closed without merging**
