### PR TITLE
fix mcdata import in trader example

### PR DESCRIPTION
**Pull request by plexigras**
autoversion is making trouble again.

### CODE REVIEW

**Comment by rom1504** [comment]
if we're using it in the examples, I think inject_allowed should be in the doc

**Comment by rom1504** [comment]
(ie I had to look at the code to know what it is)

**Comment by plexigras** [comment]
maybe doing `bot._client.once('success', ... )` would be better?

**Comment by rom1504** [comment]
would be nice to finish this, I don't like dead PRs....

**Pull request merged**
