### PR TITLE
Fixing NBT and Name settings in modifyBook function

### PR DESCRIPTION
**Pull request by adambrangenberg**
In prismarine-item the property name isn't part of NBT but the Item itself. 

https://github.com/PrismarineJS/prismarine-item/blob/master/index.js#L29

### CODE REVIEW

**Comment by u9g** [comment]
Can you add a failing test that is fixed by this pr?

**Comment by TigerbyteDev** [comment]
There isn't a way to test the function directly since it's not being exported. We could test bot.writeBook() or bot.signBook() though?

**Comment by u9g** [comment]
> 

Just test anything that supposed to be fixed by this pr

**Comment by adambrangenberg** [comment]
Hey, book is currently excluded tests. Is there any specific reason for that since I'm also getting this: 
image

**Comment by adambrangenberg** [comment]
@u9g ?

**Comment by rom1504** [comment]
@adambrangenberg can you do what U9G is asking ? is anything new working now ?

**Comment by adambrangenberg** [comment]
@rom1504 as I said before, the Test is in excluded tests and also timing out or failing. Is there any specific reason for that?

**Comment by rom1504** [comment]
Probably because either the test or the implementation doesn't work. You can check what commit last changed that line with git blame

**Comment by adambrangenberg** [comment]
It's a commit from you saying "temporarily disable flaky book test", but I don't know why that would make it fail

**Comment by adambrangenberg** [comment]
I debugged it a bit more, inventory.js#L549 is causing it to timeout and loose connection (=> fail test)

**Comment by rom1504** [comment]
I can't tell whether this is correct and there is no test for it, please re open if you want to finish this

**Pull request closed without merging**
