### PR TITLE
Change findblocks into promise have a sense?

### PR DESCRIPTION
**Pull request by sefirosweb**
Hi guys, I have been noticed that my bot sometimes freezes, I have detected that if I run findblock to search in a large radius, this causes that the bot freeze until the search is finished,

I think it would be a good idea change the method to a promise, and give it a short wait for the bot to exchange the action processes with the search and this not freeze the bot,

The change is simple, which will cause users to have to adapt their code to a promise

Obviously the performance is worse; the same test for "normal"/"promise" is 3-4 times slower,
What this slowness in my opinion compensates for the bot being much "fresher" in these actions without blocking,

image

The important code are only in block.js
Change findblocks into promise have a sense?

### CODE REVIEW

**Comment by rom1504** [comment]
I think we should rather introduce a new method (potentially using a
partially common implementation with the current method) rather than make
this breaking change.

**Comment by extremeheat** [comment]
Also, yielding to the event loop inside of any hot/iterative code is really bad as that prevents any JIT optimizations, on top of the event loop overhead (copying memory, waiting, etc). If it's really necessary to split up work, you would need to find a better algorithm to segment the data and yield as little as possible (maybe a few times depending on search area) to make it optimal. 

I think a better solution would be to profile the existing code and see if synchronous optimizations could be made (reducing copies, type conversions, checks, etc). As of right now, it seems findBlock() is running through every block in the box, when it could be exiting early on the first match. That's an easy optimization.

**Comment by sefirosweb** [comment]
I don't think it can help much in optimizing the code, I don't understand it very well, and when I want to see the variable types I see that many of them are not complete.

image

If you want I can make a new method "searchBlock" & "searchBlocks" that use a common code or most of it

**Comment by extremeheat** [comment]
> I don't think it can help much in optimizing the code

It will, pushing things to do later will make things slower, not faster. It will still block your program, including timers. The only way to not block aside a worker is to do less operations or more efficient ones.

> I don't understand it very well, and when I want to see the variable types I see that many of them are not complete.

Use control + f to search the codebase, it's not very big or complicated code, everything is defined in a few lib/plugins files.

> If you want I can make a new method "searchBlock" & "searchBlocks" that use a common code or most of it

Echo my previous comment: As of right now, it seems findBlock() is running through every block in the box, when it could be exiting early on the first match. That's an easy optimization.

**Comment by sefirosweb** [comment]
I'm on it =)

about findBlock (one) already have fast exit on find one,
```ts
if (startedLayer !== it.apothem && blocks.length >= count) {
```

> It will, pushing things to do later will make things slower, not faster. It will still block your program, including timers. The only way to not block aside a worker is to do less operations or more efficient ones.

Yes and not, yes is more slower, but the bot dosent freeze on to do this operation, (of course this affect to the rest of bot while are executing )

anyways i try to see if it can also be improved without promises

**Comment by szdytom** [comment]
Possibly related to #3216.

**Comment by extremeheat** [comment]
> anyways i try to see if it can also be improved without promises

One of the best ways to make things faster is by minimizing memory allocations/copies, especially in hot code. Simplifying the code helps, but be cautious here since less code doesn't mean faster, if that "less code" is just an abstraction for really complex code under the hood. https://github.com/PrismarineJS/prismarine-physics/pull/111/commits/d29774ae4ca426d87a5209a9dc5e92aa45458b7c is a good example for that, as lots of garbage from temporary objects would be created in hot code.

Also, moving the world data and these findBlock methods to prismarine-world per #334 would make it easier to remove where the bottlenecks are in the current code.

**Comment by rom1504** [comment]
ci is failing

**Comment by sefirosweb** [comment]
I tried to improve the optimization but without results..

Finally are you interested to merge this pr?

**Comment by rom1504** [comment]
yeah actually reading the previous discussion it seems this PR is not really helping right? maybe we should just close it?

**Comment by sefirosweb** [comment]
There are contrary opinions, I think so, but I do not have the knowledge to improve performance, if perhaps it is not interesting we can close the pr

**Comment by rom1504** [comment]
ok

**Pull request closed without merging**
